name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runner-job:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: password
          POSTGRES_DB: remixedanswersdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Is it running?
        run: docker container ls
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Push DB changes
        run: bun db:push
        env:
          DATABASE_URL: postgres://postgres:password@0.0.0.0:5432/remixedanswersdb
      - name: Seed database
        run: bun db:seed
      - name: Run Playwright tests
        run: bunx playwright test
        env:
          DATABASE_URL: postgres://postgres:password@0.0.0.0:5432/remixedanswersdb
